### ISSUE TITLE
No output apart from "Connection with client made"

### ISSUE THREAD

**Issue by hax0rgb** [ChrisMcMStone/spinner#4]
I tried to run app vulnerable to certificate and hostname validation and I don't see anything apart from "Connection with client made" in the tool.
It would be better if there is any demo or tutorial of how to find flaws using this tool.
I am attaching the screenshot for your reference.

<img width="815" alt="screen shot 2018-01-19 at 4 59 50 pm" src="https://user-images.githubusercontent.com/13043764/35149102-e2d8f230-fd3a-11e7-9321-8d24b9ce3fce.png">

**Comment by ChrisMcMStone** [comment]
Hi, I have just pushed an update to the log messages that will be printed when this situation occurs. What's happening here is your device is connecting with Spinner but Spinner doesn't know where to redirect the connection. You need to make sure that your device is using Spinner's IP for DNS requests, or set a manual redirect host with the `-m` flag.

**Comment by hax0rgb** [comment]
Hi Chris,

Thanks for this.
But even after specifying the redirect host with -m flag, i m not getting a valid output. Is there something i am missing here?

<img width="1266" alt="screen shot 2018-01-20 at 8 30 03 am" src="https://user-images.githubusercontent.com/13043764/35179246-6768eca4-fdbc-11e7-95f9-d39da00a3995.png">

**Comment by ChrisMcMStone** [comment]
@gaurang8492 can you please pull the latest commit and try again? Thanks

**Comment by hax0rgb** [comment]
Hi Chris,

Tried again. Now this is only what i see on loading a vulnerable app.

<img width="927" alt="screen shot 2018-01-23 at 3 40 17 pm" src="https://user-images.githubusercontent.com/13043764/35270056-e905557e-0053-11e8-8f30-395a3d019c69.png">

**Comment by ChrisMcMStone** [comment]
@gaurang8492 The problem with the app your testing is it appears to be making TLS connections with an older version of TLS (e.g. SSLv2 or SSLv3). This proxy current only supports record parsing of TLS 1.2. There are plans to extend the support of this tool to those protocols. However, at this stage I'm afraid the tool won't work for you.
